// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentMeetingPlanner.Data;

#nullable disable

namespace SacramentMeetingPlanner.Migrations
{
    [DbContext(typeof(SacramentMeetingPlannerContext))]
    [Migration("20220719011425_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SacramentMeetingPlanner.Models.Hymn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HymnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HymnTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HymnType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hymn");
                });

            modelBuilder.Entity("SacramentMeetingPlanner.Models.Plan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chorister")
                        .HasColumnType("TEXT");

                    b.Property<int>("Closing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conducting")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Intermediate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OP")
                        .HasColumnType("TEXT");

                    b.Property<int>("Opening")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pianist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presiding")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerOneSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerThreeSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerTwoSubject")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Plan");
                });
#pragma warning restore 612, 618
        }
    }
}
